### ISSUE TITLE
nukkit

### ISSUE THREAD

**Issue by misha1** [Nukkit-Plugins/LetMeHome#2]
help me please, i can`t install nukkit in windows 10 :c

**Comment by seompark** [comment]
First, u need to install and setup the jdk(Environment path). Then u can start nukkit on cmd or ur own batch file; type 'java -jar <nukkitfile>

**Comment by misha1** [comment]
how open start.cmd? what is the nukkitfile?

**Comment by seompark** [comment]
Nukkit file that u download on jenkins like 'http://ci.mengcraft.com:8080/job/nukkit/', start.cmd or start.bat is the file u should make yourself. make the 'start.bat' file and edit it by text editor; write ' java -jar <nukkit file. ex)nukkit-1.0-SNAPSHOT.jar>'

**Comment by seompark** [comment]
한국인이세요?

**Comment by misha1** [comment]
thank!)

**Comment by moca127** [comment]
네 한국인 입니다.

**Comment by angelless** [comment]
네.저도 한국인입니다

**Comment by seompark** [comment]
이거 소스 극혐인데 그만 보세요 ㅡㅡ
